name: CI pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package jacoco:report --file pom.xml 

    - name: Coveralls
      run: mvn coveralls:report --define repoToken=${{ secrets.COVERALL_REPO_TOKEN }}
